# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          #export DOTNET_ROOT=$HOME/.dotnet
          #export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
          
          dotnet tool uninstall -g Amazon.Lambda.Tools          
          dotnet tool install -g Amazon.Lambda.Tools
          cd MyFunction/src/MyFunction
          dotnet lambda package
          echo test, and deploy your project.
